### ISSUE TITLE
DS918+ DSM 7.0 When to support？

### ISSUE THREAD

**Issue by lai-zai** [bb-qq/r8152#95] opened 2021-02-02 11:41 UTC
Is there a solution?

**Comment by cesar9270** [comment] 2021-02-03 20:45
exactly the same request for me

**Comment by cesar9270** [comment] 2021-02-03 20:55
At least someone made a fork and managed to make it work with DSM 7 beta on DS415
https://github.com/bb-qq/r8152/issues/75#issuecomment-765859421

**Comment by lai-zai** [comment] 2021-02-04 14:42
> At least someone made a fork and managed to make it work with DSM 7 beta on DS415
> [#75 (comment)](https://github.com/bb-qq/r8152/issues/75#issuecomment-765859421)

Other series seem to have no successful cases

**Comment by bb-qq** [comment] 2021-05-29 07:11
Duplicate of #26

**Closed by bb-qq** 2021-05-29 07:11 UTC
Labels: duplicate
