### ISSUE TITLE
Asking for a Club 3D CAC-1420 USB 3.2 Gen1 Type A to RJ45 2.5Gbps Ethernet Adapter driver for DSM 7.1.1 RC on Synology DS418play

### ISSUE THREAD

**Issue by YVES59** [bb-qq/r8152#236] opened 2022-08-13 14:10 UTC
Hello everyone !!!

I have been using the GitHub drivers for my USB Realtek 2.5GbE adapter since the beginning without any problem, many thanks for this great work of the developers !!!

Unfortunately, after the upgrade of my DS418play to DSM  7.1.1 - 42951 RC from DSM 7.1 - 42661 Update 4, the driver is no longer functionnal (even with a full reinstallation).

May I ask the opinion of the developers ?

Many thanks for your help, as this 2.5Gbs wired ethernet connection of my DS418play is very important for me. !!!!!!

Best Regards 

...... very sorry it WORKS, oddly, what you need to do is first go back to automatic DNS config for the LAN3, then switch back to your manual parameters, thereafter fully functional !!!!!!!!!!!!!!

**Comment by mrjohnpoz** [comment] 2022-08-14 20:50
Yeah seeing the same thing - see my comment on the other thread about dsm 7.1

I just had to shutdown my nas because of a planned power outage from the elec company, and was scheduled to be longer than my ups could run.

When I brought it back up, yeah had to cycle it to dhcp, let it not get an IP.. (169.254 address) then switch it back to static and it came back up.

**Comment by TheS1R** [comment] 2022-08-15 23:19
I have two DS718+ (apollolake) also with DSM 7.1.1-42951 RC. I experienced the same failure with static IP addresses. My workaround was to manually assign static IP addresses in my router (Asus GT-AX6000 with Merlin firmware) and have the NASs obtain the static addresses via DHCP.

**Comment by mrjohnpoz** [comment] 2022-08-16 00:06
That is an option if you have dhcp server running on the network your connected to - but in my setup its just direct connection between my pc and the nas for 2.5ge transfer of data between the two.

Guess I could run dhcp server on my PC for the nas connection - but use to work before.  Its not the end of the world since only time I really reboot nas is update or some extended power outage which are rare.

It never use to be an issue, have been running this for quite some time with multiple updates to the DSM software and the bb-qq driver version.

**Comment by TheS1R** [comment] 2022-08-16 01:02
Used to work in my case as well.

**Comment by mrjohnpoz** [comment] 2022-08-16 01:23
I think something changed in 7.1.1, hope that bb-qq figures it out.  

Any info I can provide just ask.. But doesn't look like he has seen the thread yet.

**Comment by bb-qq** [comment] 2022-08-20 06:54
Since [2.15.0-8](https://github.com/bb-qq/r8152/releases/tag/2.15.0-8) I have changed the storage location for persisting network setting. I guess this is the cause of this issue. 

I expected that when the system goes to shut down, the current network setting would be stored new location. But it seems to be failed.

If the same problem occurs every time you reboot, try to Stop&Start the driver from the Package Center. This will ensure that your settings are saved.
If the problem occurs only once and the setting seems to persist now, the settings have been saved correctly and you will not have the same problem in the future.

**Comment by hhessel** [comment] 2022-08-20 11:15
@bb-qq I'm not facing the same problem as above that my static ip settings are for the Club3D interface are visible but seemly not functional after a reboot. DS Assistant reports the following after the reboot:

![image](https://user-images.githubusercontent.com/225331/185743371-5fd05adc-0c24-4381-bbb9-25ac373a970c.png)

So it shows that there is manual IP address assigned but the IP address is not reachable even though if I use another interface to connect it shows in DSM. I have to switch the 2,5GB interface to another static IP and then back to the original IP. 

I tried your proposed solution of stopping and starting driver (over another interface) and even reinstalling it. Unfortunately always with the same problem afterwards. Happy to support or help in case necessary. Thanks

**Comment by bb-qq** [comment] 2022-08-20 12:23
I will check the behavior once my NAS receives the 7.1.1 rollout release.

**Comment by hhessel** [comment] 2022-08-20 12:25
@bb-qq Thanks, probably the better approach than manually updating to 7.1.1. like it ;)

**Comment by mrjohnpoz** [comment] 2022-08-20 13:05
> Club3D interface are visible but seemly not functional after a reboot

Mine were visible in the dsm setting, but if you actually looked on the interfaces with ifconfig from ssh to nas then they were not there.  I will check next time I reboot the nas to see what happens I have stopped and started the driver.

**Comment by bb-qq** [comment] 2022-10-09 06:21
(Link to #246)

Could you try this test version?
https://github.com/bb-qq/r8152/releases/download/2.16.3-1/r8152-apollolake-2.16.3-2test.spk

**Comment by blasiusx** [comment] 2022-10-09 08:16
Seee my comment at

https://github.com/bb-qq/r8152/issues/246#issuecomment-1272484723

It works fine for me. Thank you very much!!!

**Comment by bb-qq** [comment] 2022-10-11 14:14
Thank you. I close this issue since officially versioned drivers have been released.
https://github.com/bb-qq/r8152/releases/tag/2.16.3-2

**Closed by bb-qq** 2022-10-11 14:14 UTC
Labels: bug

**Comment by mrjohnpoz** [comment] 2022-10-11 14:20
@bb-qq is there any reason to change to this version vs the test one?

**Comment by bb-qq** [comment] 2022-10-11 14:23
The functionality of the driver is exactly the same to the test version, with only some improvements to the logging.
