### ISSUE TITLE
Need support for Synology DS414 (Marvell Armada XP MV78230) with RTL8156 2.5G.Thanks a lot.

### ISSUE THREAD

**Issue by Ashfu** [bb-qq/r8152#124] opened 2021-06-04 09:00 UTC

**Comment by dreimer1986** [comment] 2021-06-05 11:07
No need for a description and no need to SEARCH!
Duplicate of: https://github.com/bb-qq/r8152/issues/30

**Comment by bb-qq** [comment] 2021-07-11 01:23
Meged to #30.

**Closed by bb-qq** 2021-07-11 01:23 UTC
Labels: duplicate
