### ISSUE TITLE
Will it appear in dsm7 in the future?

### ISSUE THREAD

**Issue by akimolll** [bb-qq/r8152#113] opened 2021-04-17 14:12 UTC
This is really wonderful. It has saved a lot of people! Will it appear in the future installed version of dsm7? I hope this day will come as soon as possible, dsm7 is the future! Always support!

**Comment by Gensplejs** [comment] 2021-05-22 14:04
I just tested with DSM7.
The package is disabled after the update and when uninstalled it and then attempted to reinstall is says the package is in an invalid file format.

**Comment by bb-qq** [comment] 2021-05-29 07:10
Duplicate of #26 # #

**Closed by bb-qq** 2021-05-29 07:10 UTC
